### PR TITLE
add cols parameter to StandardScaler 

### PR DESCRIPTION
**Pull request by garzillo**
Enabling StandardScaler() be used for only partial columns for originally fit dataframe with 'cols' parameter.

eg.
`ss = StandardScaler()`
`ss.fit(df[['a','b','c']]`
`ss.transform(df[['c']], cols=['c'])`

### CODE REVIEW

**Comment by dfd** [comment]
Do we want to do it this way, or specify the columns in the __init__ function?

If we put it in the init function, then the object will hold onto it during both the pipeline fitting and transforming.  That may require the user to create one StandardScaler per use case, but I think it is more useful in the context of pipeline creations.  What do you think?

**Comment by garzillo** [comment]
It seems like two different use cases:

1. What you describe seems useful for applying standardization to only the specified columns. This would be a more convenient alternative to using a FeatureUnion to separate out the fields to standardize.

2. The use case I was thinking of was when a StandardScaler is initially fit on several fields, but then you later want to use it to transform/inverse_transform only a subset of those fields. This is definitely a less common use case, but it's been something we've been doing a lot of lately - fitting many fields on training data and then later transforming/inverse_transforming select fields on test data (especially target fields for modeling).

What do you think of adding what you describe in the __init__ function and renaming the current commit's 'cols' parameter to something like 'subset_cols' for clarity?

**Comment by garzillo** [comment]
@dfd Updated to have both options from discussion above:

**1. columns parameter in init**

```python
ss = StandardScaler(columns=['a', 'c'])
ss.fit_transform(df['a', 'b', 'c'])
```
This will only apply the transformation on whichever columns you specify, but still maintain and return the non-transformed columns.

**2. partial_cols parameter in transform/inverse_transform**

```python
ss = StandardScaler()
ss.fit(df['a', 'b', 'c'])
a_transformed = ss.transform(df, partial_cols=['a'])
```
or
```python
ss = StandardScaler()
ss.fit(df['a', 'b', 'c'])
a_transformed = ss.transform(df['a'], partial_cols=['a'])
```
This allows transforming subsets of the originally fit dataframe.

**Comment by dfd** [comment]
I found a way you should be able to change the pull request to the development branch:

https://blog.github.com/2016-08-15-change-the-base-branch-of-a-pull-request/

Can we try this?  Not sure if it will require you to rebase or not.

**Pull request merged**
